---
name: IdViewer
main: kim\present\idviewer\IdViewer
version: 1.0.0
build_number: 0
api: [ 4.0.0 ]
author: PresentKim
description: Utility that makes it easy to check the IDs of items and blocks

commands:
  idv:
    description: Toggle the ID view
    permission: idv.cmd

permissions:
  idv.cmd:
    description: /idv command
    default: op
...