name : Build Artifact

on :
  push :

jobs :
  build :
    name : Build Artifact
    runs-on : ubuntu-20.04
    strategy :
      fail-fast : false

    steps :
      - uses : actions/checkout@v2
        with :
          submodules : true

      - uses : shivammathur/setup-php@2.12.0
        with :
          php-version : 8.0

      - name : Build numbering
        run : |
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          echo "Build number: $BUILD_NUMBER"
          sed -i -E "s/version\: ([0-9]+)\.([0-9]+)\.([0-9]+)/\0-BUILD${BUILD_NUMBER}/g" ${{ github.workspace }}/plugin.yml

      - name : Download DevTools/ConsoleScript.php
        run : |
          mkdir ${{ github.workspace }}/build
          wget -O ${{ github.workspace }}/build/build.php https://raw.githubusercontent.com/pmmp/DevTools/master/src/DevTools/ConsoleScript.php

      - name : Build PocketMine-MP.phar
        run : php -dphar.readonly=0 ${{ github.workspace }}//build/build.php --make ${{ github.workspace }}/ --out ${{ github.workspace }}/build/artifact.phar

      - name : Upload release artifacts
        uses : actions/upload-artifact@v2
        with :
          name : release_artifacts
          path : ${{ github.workspace }}/build/artifact.phar
